---
# tasks file for gcloudsdk - EL

- name: Adding repository {{ gcloudsdk_repo_el }} on EL based systems.
  yum_repository:
    name: "{{ gcloudsdk_repo_el_name }}"
    description: "{{ gcloudsdk_repo_el_description }}"
    baseurl: "{{ gcloudsdk_repo_el }}"
    gpgcheck: "{{ gcloudsdk_repo_el_gpgcheck }}"
    repo_gpgcheck: "{{ gcloudsdk_repo_el_repogpgcheck }}"
    gpgkey:
      - "{{ gcloudsdk_el_gpg_yum_key }}"
      - "{{ gcloudsdk_el_gpg_rpm_key }}"
    enabled: "{{ gcloudsdk_repo_el_enabled }}"
    file: "{{ gcloudsdk_repo_el_filename }}"
    state: "{{ gcloudsdk_repo_desired_state }}"
- name: Installing {{ gcloudsdk_app_name }} on EL based systems.
  yum:
    name: "{{ gcloudsdk_app_name }}"
    state: "{{ gcloudsdk_desired_state }}"
    update_cache: yes
